### ISSUE TITLE
ItemUse, ItemList

### ISSUE THREAD

**Issue by UmaPedra** [The-West-Scripts/TW-Toolkit#4]
Hi, i am trying to update the script by myself, with the latest Xmas gifts, i insert the desired items ID into ItemList, but after saving and refreshing game, i can't open in mass those gifts, any solution?

**Comment by UmaPedra** [comment]
If you don't mind, you could just take mine ItemList, replace and release a update for your script. Would be much better, so you can hit most of the users

itemList: [374000, 2540000, 2540000, 2685000, 2297000, 21340000, 21341000, 21342000, 21343000, 50991000, 2491000, 1888000, 2227000, 2345000, 2559000, 2560000, 50605000, 51066000, 51783000, 51835000, 52053000 , 2721000, 926000, 2194000, 2299000, 2298000, 2359000, 2361000, 2360000, 2579000, 2580000, 2646000, 2645000, 50002000, 50003000, 50384000, 50082000, 50168000, 50170000, 50169000, 50348000, 377000, 2488000, 2489000, 2490000, 2687000, 2689000, 50001000, 50385000, 50386000, 50387000, 50391000, 376000, 52293000, 51776000, 1975000, 1976000, 2675000, 2676000, 2561000, 2562000, 13711000, 2690000, 379000, 50382000, 50839000, 50855000, 51156000, 51324000, 2136000, 2393000, 2137000, 2394000, 2138000, 2395000, 2139000,2559000,51468000,2560000,51810000,51921000,2196000,2197000,2198000,2199000,2200000],

**Comment by Thathanka-Iyothanka** [comment]
Hi
Thanks, I will take care of that soon.
Feel free to submit a PR if you'd like to suggest further changes.

Happy holidays

**Comment by Thathanka-Iyothanka** [comment]
v1.53
